# Generated by Django 5.0.11 on 2025-05-07 04:42

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_visit_date', models.DateField(blank=True, null=True, verbose_name='last in')),
                ('karma', models.IntegerField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='A Brief description of the Path', max_length=1000)),
                ('refcode', models.CharField(max_length=13, verbose_name='RefCode')),
                ('apprentice', models.ManyToManyField(help_text='Add a new Apprentice to this Learning Path', related_name='learning_paths', to='catalog.guache')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='author_paths', to='catalog.guache')),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.UUIDField(default=uuid.uuid4, help_text='Unique UUID Serial for this particular learning path')),
                ('name', models.CharField(max_length=500, null=True)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('w', 'Walking'), ('m', 'Maintenance'), ('d', 'In debt'), ('l', 'Lost'), ('c', 'Completed path')], default='w', help_text='Status of the Learning Path', max_length=1)),
                ('birth', models.DateField(blank=True, null=True)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('apprentice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.path')),
            ],
            options={
                'ordering': ['birth'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Knowledge task item...', max_length=200, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.guache')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='task',
            field=models.ManyToManyField(help_text='Select tasks for this path', to='catalog.task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='task_name_case_insensitive_unique', violation_error_message='Task already exists (case insensitive match)'),
        ),
    ]
