# Generated by Django 5.0.11 on 2025-05-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learning',
            options={'ordering': ['birth'], 'permissions': (('can_mark_completed', 'Set Path as Completed...'),)},
        ),
    ]
