# Generated by Django 5.0.11 on 2025-02-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='apprentice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.guache'),
        ),
        migrations.AddField(
            model_name='path',
            name='apprentice',
            field=models.ManyToManyField(help_text='Add a new Apprentice to this Learning Path', related_name='learning_paths', to='catalog.guache'),
        ),
        migrations.AddField(
            model_name='path',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='author_paths', to='catalog.guache'),
        ),
    ]
