# Generated by Django 5.0.11 on 2025-05-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_learning_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learning',
            options={'ordering': ['birth']},
        ),
    ]
