# Generated by Django 5.0.11 on 2025-02-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_task_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
