# Generated by Django 5.0.11 on 2025-02-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_learning_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learning',
            options={'ordering': ['birth']},
        ),
        migrations.RenameField(
            model_name='learning',
            old_name='begin',
            new_name='last_visit',
        ),
    ]
