# Generated by Django 5.0.11 on 2025-05-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_learning_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learning',
            options={'ordering': ['birth'], 'permissions': (('can_mark_completed', 'Set Learning Path as Completed...'),)},
        ),
    ]
