# Generated by Django 5.0.14 on 2025-12-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_learning_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learning',
            options={'ordering': ['birth'], 'permissions': (('can_mark_completed', 'Set Learning Path as Completed...'), ('can_mark_changed', 'Set Learning as changed'))},
        ),
        migrations.AlterField(
            model_name='guache',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='birth'),
        ),
    ]
