# Generated by Django 5.0.11 on 2025-02-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_guache_date_of_birth_guache_last_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
